#!/bin/bash

# Frontend Route Protection Test Script
# Tests JWT token-based route protection on the frontend

set -e

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🔒 Testing Frontend Route Protection${NC}"
echo "======================================"
echo ""

# Check if frontend is running
FRONTEND_URL="${FRONTEND_URL:-http://localhost:5173}"

echo "Checking frontend server..."
if curl -s "$FRONTEND_URL" > /dev/null 2>&1; then
  echo -e "${GREEN}✅ Frontend is running at $FRONTEND_URL${NC}"
else
  echo -e "${RED}❌ Frontend is not running${NC}"
  echo "   Start the frontend with: cd frontend && npm run dev"
  exit 1
fi

echo ""
echo -e "${BLUE}📋 Manual Test Checklist${NC}"
echo "=========================="
echo ""

echo "Test 1: Access Protected Route Without Token"
echo "---------------------------------------------"
echo "1. Open browser to: $FRONTEND_URL"
echo "2. Open DevTools Console"
echo "3. Clear localStorage:"
echo "   localStorage.clear()"
echo "4. Navigate to: $FRONTEND_URL/#/dashboard"
echo ""
echo "Expected Results:"
echo -e "${GREEN}✓${NC} Redirected to login page"
echo -e "${GREEN}✓${NC} Console shows: '❌ No token, redirecting to login from /dashboard'"
echo -e "${GREEN}✓${NC} Console shows: '🔒 Access denied to /dashboard - redirecting to login'"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo "Test 2: Login and Access Protected Routes"
echo "------------------------------------------"
echo "1. On login page, enter credentials"
echo "2. Click 'Sign In'"
echo "3. Check console for messages"
echo "4. Should redirect to dashboard"
echo ""
echo "Expected Console Output:"
echo -e "${GREEN}✓${NC} '🔵 Attempting login'"
echo -e "${GREEN}✓${NC} '✅ Login successful'"
echo -e "${GREEN}✓${NC} '✅ Token stored in localStorage'"
echo -e "${GREEN}✓${NC} '✅ Token found, access granted to /dashboard'"
echo ""
echo "5. Verify token in localStorage:"
echo "   localStorage.getItem('authToken')"
echo "   Should show a JWT token string"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo "Test 3: Navigate Between Protected Routes"
echo "------------------------------------------"
echo "1. While logged in, click 'Create Payment' in nav"
echo "2. Check console"
echo "3. Navigate to dashboard"
echo "4. Check console"
echo ""
echo "Expected Console Output:"
echo -e "${GREEN}✓${NC} '✅ Token found, access granted to /create'"
echo -e "${GREEN}✓${NC} '✅ Token found, access granted to /dashboard'"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo "Test 4: Logout"
echo "--------------"
echo "1. While logged in, click profile dropdown"
echo "2. Click 'Sign Out'"
echo "3. Check console"
echo ""
echo "Expected Console Output:"
echo -e "${GREEN}✓${NC} '🔵 Logout button clicked'"
echo -e "${GREEN}✓${NC} '🔵 User logging out'"
echo -e "${GREEN}✓${NC} '✅ Logout complete'"
echo -e "${GREEN}✓${NC} '   Token cleared from localStorage'"
echo ""
echo "4. Verify token is cleared:"
echo "   localStorage.getItem('authToken')"
echo "   Should show: null"
echo ""
echo "5. Try to access /dashboard"
echo "   Should redirect to login"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo "Test 5: Google OAuth (if configured)"
echo "------------------------------------"
echo "1. On login page, click 'Sign in with Google'"
echo "2. Authorize on Google"
echo "3. Check console after redirect"
echo ""
echo "Expected Console Output:"
echo -e "${GREEN}✓${NC} '🔵 Google OAuth callback received'"
echo -e "${GREEN}✓${NC} '✅ JWT token received from backend'"
echo -e "${GREEN}✓${NC} '✅ Token stored in localStorage as \"authToken\"'"
echo -e "${GREEN}✓${NC} '✅ User profile refreshed from /api/auth/me'"
echo -e "${GREEN}✓${NC} '⏩ Navigating to dashboard'"
echo -e "${GREEN}✓${NC} '✅ Token found, access granted to /dashboard'"
echo ""
read -p "Press Enter when test is complete (or skip if OAuth not configured)..."

echo ""
echo "Test 6: Invalid Token"
echo "---------------------"
echo "1. Set invalid token:"
echo "   localStorage.setItem('authToken', 'invalid_token_here')"
echo "2. Refresh page or navigate to /dashboard"
echo "3. Check console"
echo ""
echo "Expected Results:"
echo -e "${GREEN}✓${NC} Token validation fails"
echo -e "${GREEN}✓${NC} Token cleared from localStorage"
echo -e "${GREEN}✓${NC} Redirected to login"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo "Test 7: Token Persistence Across Page Refresh"
echo "----------------------------------------------"
echo "1. Login successfully"
echo "2. Verify you're on dashboard"
echo "3. Refresh the page (F5 or Ctrl+R)"
echo "4. Check console"
echo ""
echo "Expected Results:"
echo -e "${GREEN}✓${NC} Token still exists in localStorage"
echo -e "${GREEN}✓${NC} User remains logged in"
echo -e "${GREEN}✓${NC} Dashboard still accessible"
echo -e "${GREEN}✓${NC} Console shows: '✅ Token found, access granted'"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo "Test 8: Direct URL Access"
echo "-------------------------"
echo "1. Logout if logged in"
echo "2. In address bar, navigate to: $FRONTEND_URL/#/create"
echo "3. Check console and page"
echo ""
echo "Expected Results:"
echo -e "${GREEN}✓${NC} Redirected to login page"
echo -e "${GREEN}✓${NC} Console shows: '❌ No token, redirecting to login'"
echo ""
echo "4. Login"
echo "5. In address bar, navigate to: $FRONTEND_URL/#/create"
echo ""
echo "Expected Results:"
echo -e "${GREEN}✓${NC} Create payment page loads"
echo -e "${GREEN}✓${NC} Console shows: '✅ Token found, access granted to /create'"
echo ""
read -p "Press Enter when test is complete..."

echo ""
echo -e "${BLUE}═══════════════════════════════════════${NC}"
echo -e "${GREEN}🎉 All Manual Tests Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════${NC}"
echo ""

echo "Summary of Route Protection:"
echo "----------------------------"
echo -e "${GREEN}✅${NC} Protected routes require authentication"
echo -e "${GREEN}✅${NC} Token stored in localStorage"
echo -e "${GREEN}✅${NC} Automatic redirect to login when unauthenticated"
echo -e "${GREEN}✅${NC} Logout clears token and redirects"
echo -e "${GREEN}✅${NC} Token persists across page refreshes"
echo -e "${GREEN}✅${NC} Invalid tokens are cleared automatically"
echo -e "${GREEN}✅${NC} Google OAuth integration working"
echo -e "${GREEN}✅${NC} Comprehensive logging for debugging"
echo ""

echo "Protected Routes:"
echo "  🔒 /dashboard"
echo "  🔒 /create"
echo "  🔒 /payment/:id"
echo ""

echo "Public Routes:"
echo "  🌐 /login"
echo "  🌐 /register"
echo "  🌐 /auth/google/callback"
echo ""

echo "Token Location:"
echo "  localStorage key: 'authToken'"
echo ""

echo "For more details, see:"
echo "  • frontend/PHASE6_COMPLETE.md"
echo "  • frontend/PHASE6_QUICK_REFERENCE.md"
echo "  • frontend/PHASE6_FLOW_DIAGRAM.md"
echo ""
