#!/bin/bash

echo "🔍 Testing Google OAuth Flow with Detailed Logging"
echo "=================================================="
echo ""
echo "This script will test the OAuth endpoints and show you where to check logs."
echo ""

BACKEND_URL="http://127.0.0.1:3467"

# Test 1: OAuth initiation
echo "📋 Test 1: Testing OAuth Initiation Route"
echo "   GET $BACKEND_URL/api/auth/google"
echo ""

RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$BACKEND_URL/api/auth/google" 2>&1)

echo "   Response: HTTP $RESPONSE"

if [ "$RESPONSE" = "302" ]; then
  echo "   ✅ OAuth initiation working (302 redirect)"
elif [ "$RESPONSE" = "503" ]; then
  echo "   ⚠️  OAuth not configured (503)"
elif [ "$RESPONSE" = "500" ]; then
  echo "   ❌ Server error (500)"
else
  echo "   ⚠️  Unexpected response: $RESPONSE"
fi

echo ""
echo "=================================================="
echo "📝 Check Backend Logs"
echo "=================================================="
echo ""
echo "To see the detailed logging, check your backend output:"
echo ""
echo "If running in terminal:"
echo "   Look at the terminal where 'node server.js' is running"
echo ""
echo "If running in background:"
echo "   tail -f /home/techmedaddy/projects/payeazie/backend/server.log"
echo ""
echo "If running in Docker:"
echo "   docker logs -f payeazie-backend"
echo ""
echo "=================================================="
echo "🔍 Expected Log Output"
echo "=================================================="
echo ""
echo "When you click 'Sign in with Google' and complete OAuth:"
echo ""
echo "1️⃣  Route Entry:"
echo "   ✅ /api/auth/google route hit"
echo "   Request URL: /api/auth/google"
echo ""
echo "2️⃣  Passport Authentication:"
echo "   ✅ Calling passport.authenticate for Google OAuth..."
echo "   [Redirects to Google]"
echo ""
echo "3️⃣  Callback Entry:"
echo "   ✅ /api/auth/google/callback route hit"
echo "   Query params: { code: '...', state: '...' }"
echo ""
echo "4️⃣  Strategy Callback:"
echo "   ✅ Google Strategy callback invoked"
echo "   Profile ID: 123456789"
echo "   Profile emails: [ { value: 'user@gmail.com', verified: true } ]"
echo "   Profile name: John Doe"
echo ""
echo "5️⃣  User Processing:"
echo "   ✅ Processing user with email: user@gmail.com"
echo "   ✅ Found existing user by Google ID: abc-123"
echo "   (or) ✅ Creating new user from Google account"
echo ""
echo "6️⃣  Authentication Complete:"
echo "   ✅ request.user: { id: 'abc-123', email: 'user@gmail.com', ... }"
echo "   ✅ Calling googleAuthCallback controller..."
echo ""
echo "7️⃣  JWT Issuance:"
echo "   ✅ googleAuthCallback() called"
echo "   ✅ User verified in controller: { id: 'abc-123', ... }"
echo "   ✅ JWT issued: eyJhbGciOiJIUzI1NiIs..."
echo "   Token length: 180"
echo ""
echo "8️⃣  Redirect:"
echo "   ✅ Redirecting to: http://localhost:3000/#/dashboard?token=eyJhbGc..."
echo "   ✅ Google OAuth callback completed"
echo ""
echo "=================================================="
echo "❌ Error Scenarios"
echo "=================================================="
echo ""
echo "If OAuth fails, you'll see:"
echo "   ❌ Google OAuth error: [error message]"
echo "   Error message: [detailed message]"
echo "   Error stack: [full stack trace]"
echo ""
echo "Common errors:"
echo "   - ❌ No email in Google profile"
echo "   - ❌ Google returned error: access_denied"
echo "   - ❌ No user returned from passport"
echo "   - ❌ No user in request.user"
echo ""
echo "=================================================="
echo "🎯 Manual Browser Test"
echo "=================================================="
echo ""
echo "1. Open: http://localhost:3000"
echo "2. Click: 'Sign in with Google'"
echo "3. Complete Google authentication"
echo "4. Watch backend logs for the flow above"
echo "5. Should redirect to dashboard with token"
echo ""
echo "✅ Logging is now active - test OAuth to see detailed trace!"
